// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/proto/status.proto

package status

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusMessage) Reset() {
	*x = StatusMessage{}
	mi := &file_internal_proto_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMessage) ProtoMessage() {}

func (x *StatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMessage.ProtoReflect.Descriptor instead.
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_status_proto_rawDescGZIP(), []int{0}
}

func (x *StatusMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StatusMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_internal_proto_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_status_proto_rawDescGZIP(), []int{1}
}

func (x *StatusRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_internal_proto_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_status_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_internal_proto_status_proto protoreflect.FileDescriptor

const file_internal_proto_status_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/status.proto\x12\x06status\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\rStatusMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"#\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"R\n" +
	"\x0eStatusResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code2\xc6\x01\n" +
	"\rStatusService\x12:\n" +
	"\tGetStatus\x12\x15.status.StatusRequest\x1a\x16.status.StatusResponse\x12:\n" +
	"\tSetStatus\x12\x15.status.StatusMessage\x1a\x16.status.StatusResponse\x12=\n" +
	"\fDeleteStatus\x12\x15.status.StatusRequest\x1a\x16.status.StatusResponseB\tZ\a/statusb\x06proto3"

var (
	file_internal_proto_status_proto_rawDescOnce sync.Once
	file_internal_proto_status_proto_rawDescData []byte
)

func file_internal_proto_status_proto_rawDescGZIP() []byte {
	file_internal_proto_status_proto_rawDescOnce.Do(func() {
		file_internal_proto_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_status_proto_rawDesc), len(file_internal_proto_status_proto_rawDesc)))
	})
	return file_internal_proto_status_proto_rawDescData
}

var file_internal_proto_status_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_status_proto_goTypes = []any{
	(*StatusMessage)(nil),         // 0: status.StatusMessage
	(*StatusRequest)(nil),         // 1: status.StatusRequest
	(*StatusResponse)(nil),        // 2: status.StatusResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_internal_proto_status_proto_depIdxs = []int32{
	3, // 0: status.StatusMessage.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: status.StatusService.GetStatus:input_type -> status.StatusRequest
	0, // 2: status.StatusService.SetStatus:input_type -> status.StatusMessage
	1, // 3: status.StatusService.DeleteStatus:input_type -> status.StatusRequest
	2, // 4: status.StatusService.GetStatus:output_type -> status.StatusResponse
	2, // 5: status.StatusService.SetStatus:output_type -> status.StatusResponse
	2, // 6: status.StatusService.DeleteStatus:output_type -> status.StatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_status_proto_init() }
func file_internal_proto_status_proto_init() {
	if File_internal_proto_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_status_proto_rawDesc), len(file_internal_proto_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_status_proto_goTypes,
		DependencyIndexes: file_internal_proto_status_proto_depIdxs,
		MessageInfos:      file_internal_proto_status_proto_msgTypes,
	}.Build()
	File_internal_proto_status_proto = out.File
	file_internal_proto_status_proto_goTypes = nil
	file_internal_proto_status_proto_depIdxs = nil
}
